"""
Session Metadata Plugin Parser

Parses AcquisitionDetails, ImageMetaData, and WeatherData files
generated by NINA's Session Metadata Plugin.

Supports both JSON and CSV formats.
"""

import json
import csv
import math
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
import logging

from models import (
    AcquisitionDetails,
    ImageMetaDataRecord,
    WeatherDataRecord,
    SessionMetadataResponse,
)

logger = logging.getLogger("backend.session_metadata_parser")

# Field name mappings: Plugin field names -> model field names
ACQUISITION_FIELD_MAP = {
    "TargetName": "target_name",
    "targetname": "target_name",
    "RACoordinates": "ra_coordinates",
    "racoordinates": "ra_coordinates",
    "DECCoordinates": "dec_coordinates",
    "deccoordinates": "dec_coordinates",
    "TelescopeName": "telescope_name",
    "telescopename": "telescope_name",
    "FocalLength": "focal_length",
    "focallength": "focal_length",
    "FocalRatio": "focal_ratio",
    "focalratio": "focal_ratio",
    "CameraName": "camera_name",
    "cameraname": "camera_name",
    "PixelSize": "pixel_size",
    "pixelsize": "pixel_size",
    "BitDepth": "bit_depth",
    "bitdepth": "bit_depth",
    "ObserverLatitude": "observer_latitude",
    "observerlatitude": "observer_latitude",
    "ObserverLongitude": "observer_longitude",
    "observerlongitude": "observer_longitude",
    "ObserverElevation": "observer_elevation",
    "observerelevation": "observer_elevation",
}

IMAGE_META_FIELD_MAP = {
    "ExposureNumber": "exposure_number",
    "exposurenumber": "exposure_number",
    "FilePath": "file_path",
    "filepath": "file_path",
    "FilterName": "filter_name",
    "filtername": "filter_name",
    "ExposureStart": "exposure_start",
    "exposurestart": "exposure_start",
    "ExposureStartUTC": "exposure_start_utc",
    "exposurestartutc": "exposure_start_utc",
    "Duration": "duration",
    "duration": "duration",
    "Binning": "binning",
    "binning": "binning",
    "CameraTemp": "camera_temp",
    "cameratemp": "camera_temp",
    "CameraTargetTemp": "camera_target_temp",
    "cameratargettemp": "camera_target_temp",
    "Gain": "gain",
    "gain": "gain",
    "Offset": "offset",
    "offset": "offset",
    "ADUMean": "adu_mean",
    "adumean": "adu_mean",
    "ADUMedian": "adu_median",
    "adumedian": "adu_median",
    "ADUStDev": "adu_stdev",
    "adustdev": "adu_stdev",
    "ADUMin": "adu_min",
    "adumin": "adu_min",
    "ADUMax": "adu_max",
    "adumax": "adu_max",
    "HFR": "hfr",
    "hfr": "hfr",
    "HFRStDev": "hfr_stdev",
    "hfrstdev": "hfr_stdev",
    "DetectedStars": "detected_stars",
    "detectedstars": "detected_stars",
    "FWHM": "fwhm",
    "fwhm": "fwhm",
    "Eccentricity": "eccentricity",
    "eccentricity": "eccentricity",
    "GuidingRMS": "guiding_rms",
    "guidingrms": "guiding_rms",
    "GuidingRMSArcSec": "guiding_rms_arcsec",
    "guidingrmsarcsec": "guiding_rms_arcsec",
    "GuidingRMSRA": "guiding_rms_ra",
    "guidingrmsra": "guiding_rms_ra",
    "GuidingRMSRAArcSec": "guiding_rms_ra_arcsec",
    "guidingrmsraarcsec": "guiding_rms_ra_arcsec",
    "GuidingRMSDEC": "guiding_rms_dec",
    "guidingrmsdec": "guiding_rms_dec",
    "GuidingRMSDECArcSec": "guiding_rms_dec_arcsec",
    "guidingrmsdecarcsec": "guiding_rms_dec_arcsec",
    "FocuserPosition": "focuser_position",
    "focuserposition": "focuser_position",
    "FocuserTemp": "focuser_temp",
    "focusertemp": "focuser_temp",
    "RotatorPosition": "rotator_position",
    "rotatorposition": "rotator_position",
    "PierSide": "pier_side",
    "pierside": "pier_side",
    "Airmass": "airmass",
    "airmass": "airmass",
    "MountRA": "mount_ra",
    "mountra": "mount_ra",
    "MountDec": "mount_dec",
    "mountdec": "mount_dec",
    "ImageType": "image_type",
    "imagetype": "image_type",
}

WEATHER_FIELD_MAP = {
    "ExposureNumber": "exposure_number",
    "exposurenumber": "exposure_number",
    "ExposureStart": "exposure_start",
    "exposurestart": "exposure_start",
    "ExposureStartUTC": "exposure_start_utc",
    "exposurestartutc": "exposure_start_utc",
    "Temperature": "temperature",
    "temperature": "temperature",
    "DewPoint": "dew_point",
    "dewpoint": "dew_point",
    "Humidity": "humidity",
    "humidity": "humidity",
    "Pressure": "pressure",
    "pressure": "pressure",
    "WindSpeed": "wind_speed",
    "windspeed": "wind_speed",
    "WindDirection": "wind_direction",
    "winddirection": "wind_direction",
    "WindGust": "wind_gust",
    "windgust": "wind_gust",
    "CloudCover": "cloud_cover",
    "cloudcover": "cloud_cover",
    "SkyTemperature": "sky_temperature",
    "skytemperature": "sky_temperature",
    "SkyBrightness": "sky_brightness",
    "skybrightness": "sky_brightness",
    "SkyQuality": "sky_quality",
    "skyquality": "sky_quality",
}


def _is_nan_value(value: Any) -> bool:
    """Check if a value represents NaN (string 'NaN' or actual NaN)."""
    if value is None:
        return True
    if isinstance(value, str):
        return value.lower() == "nan" or value.strip() == ""
    if isinstance(value, float):
        return math.isnan(value)
    return False


def _safe_float(value: Any) -> Optional[float]:
    """Convert value to float, returning None for NaN/invalid values."""
    if _is_nan_value(value):
        return None
    try:
        result = float(value)
        if math.isnan(result):
            return None
        return result
    except (ValueError, TypeError):
        return None


def _safe_int(value: Any) -> Optional[int]:
    """Convert value to int, returning None for invalid values."""
    if _is_nan_value(value):
        return None
    try:
        return int(float(value))
    except (ValueError, TypeError):
        return None


def _normalize_field_names(record: Dict[str, Any], field_map: Dict[str, str]) -> Dict[str, Any]:
    """Normalize field names from plugin format to model format."""
    normalized = {}
    for key, value in record.items():
        # Try exact match first
        if key in field_map:
            normalized[field_map[key]] = value
        # Try lowercase match
        elif key.lower() in field_map:
            normalized[field_map[key.lower()]] = value
        else:
            # Keep original field with snake_case conversion
            snake_key = "".join(
                ["_" + c.lower() if c.isupper() else c for c in key]
            ).lstrip("_")
            normalized[snake_key] = value
    return normalized


def parse_acquisition_details_json(file_path: str) -> Optional[AcquisitionDetails]:
    """Parse AcquisitionDetails JSON file."""
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        normalized = _normalize_field_names(data, ACQUISITION_FIELD_MAP)

        return AcquisitionDetails(
            target_name=normalized.get("target_name", "Unknown"),
            ra_coordinates=normalized.get("ra_coordinates"),
            dec_coordinates=normalized.get("dec_coordinates"),
            telescope_name=normalized.get("telescope_name"),
            focal_length=_safe_float(normalized.get("focal_length")),
            focal_ratio=_safe_float(normalized.get("focal_ratio")),
            camera_name=normalized.get("camera_name"),
            pixel_size=_safe_float(normalized.get("pixel_size")),
            bit_depth=_safe_int(normalized.get("bit_depth")),
            observer_latitude=_safe_float(normalized.get("observer_latitude")),
            observer_longitude=_safe_float(normalized.get("observer_longitude")),
            observer_elevation=_safe_float(normalized.get("observer_elevation")),
        )
    except Exception as e:
        logger.error(f"Error parsing AcquisitionDetails JSON: {e}")
        return None


def parse_acquisition_details_csv(file_path: str) -> Optional[AcquisitionDetails]:
    """Parse AcquisitionDetails CSV file."""
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                normalized = _normalize_field_names(row, ACQUISITION_FIELD_MAP)
                return AcquisitionDetails(
                    target_name=normalized.get("target_name", "Unknown"),
                    ra_coordinates=normalized.get("ra_coordinates"),
                    dec_coordinates=normalized.get("dec_coordinates"),
                    telescope_name=normalized.get("telescope_name"),
                    focal_length=_safe_float(normalized.get("focal_length")),
                    focal_ratio=_safe_float(normalized.get("focal_ratio")),
                    camera_name=normalized.get("camera_name"),
                    pixel_size=_safe_float(normalized.get("pixel_size")),
                    bit_depth=_safe_int(normalized.get("bit_depth")),
                    observer_latitude=_safe_float(normalized.get("observer_latitude")),
                    observer_longitude=_safe_float(normalized.get("observer_longitude")),
                    observer_elevation=_safe_float(normalized.get("observer_elevation")),
                )
        return None
    except Exception as e:
        logger.error(f"Error parsing AcquisitionDetails CSV: {e}")
        return None


def parse_image_metadata_json(file_path: str) -> List[ImageMetaDataRecord]:
    """Parse ImageMetaData JSON file."""
    records = []
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        if not isinstance(data, list):
            data = [data]

        for item in data:
            normalized = _normalize_field_names(item, IMAGE_META_FIELD_MAP)
            try:
                record = ImageMetaDataRecord(
                    exposure_number=_safe_int(normalized.get("exposure_number", 0)) or 0,
                    file_path=normalized.get("file_path"),
                    filter_name=normalized.get("filter_name", "Unknown"),
                    exposure_start=normalized.get("exposure_start", ""),
                    exposure_start_utc=normalized.get("exposure_start_utc", ""),
                    duration=_safe_float(normalized.get("duration")) or 0.0,
                    binning=normalized.get("binning"),
                    camera_temp=_safe_float(normalized.get("camera_temp")),
                    camera_target_temp=_safe_float(normalized.get("camera_target_temp")),
                    gain=_safe_int(normalized.get("gain")),
                    offset=_safe_int(normalized.get("offset")),
                    adu_mean=_safe_float(normalized.get("adu_mean")),
                    adu_median=_safe_float(normalized.get("adu_median")),
                    adu_stdev=_safe_float(normalized.get("adu_stdev")),
                    adu_min=_safe_int(normalized.get("adu_min")),
                    adu_max=_safe_int(normalized.get("adu_max")),
                    hfr=_safe_float(normalized.get("hfr")),
                    hfr_stdev=_safe_float(normalized.get("hfr_stdev")),
                    detected_stars=_safe_int(normalized.get("detected_stars")),
                    fwhm=_safe_float(normalized.get("fwhm")),
                    eccentricity=_safe_float(normalized.get("eccentricity")),
                    guiding_rms=_safe_float(normalized.get("guiding_rms")),
                    guiding_rms_arcsec=_safe_float(normalized.get("guiding_rms_arcsec")),
                    guiding_rms_ra=_safe_float(normalized.get("guiding_rms_ra")),
                    guiding_rms_ra_arcsec=_safe_float(normalized.get("guiding_rms_ra_arcsec")),
                    guiding_rms_dec=_safe_float(normalized.get("guiding_rms_dec")),
                    guiding_rms_dec_arcsec=_safe_float(normalized.get("guiding_rms_dec_arcsec")),
                    focuser_position=_safe_int(normalized.get("focuser_position")),
                    focuser_temp=_safe_float(normalized.get("focuser_temp")),
                    rotator_position=_safe_float(normalized.get("rotator_position")),
                    pier_side=normalized.get("pier_side"),
                    airmass=_safe_float(normalized.get("airmass")),
                    mount_ra=_safe_float(normalized.get("mount_ra")),
                    mount_dec=_safe_float(normalized.get("mount_dec")),
                    image_type=normalized.get("image_type"),
                )
                records.append(record)
            except Exception as e:
                logger.warning(f"Error parsing ImageMetaData record: {e}")
                continue

    except Exception as e:
        logger.error(f"Error parsing ImageMetaData JSON: {e}")

    return records


def parse_image_metadata_csv(file_path: str) -> List[ImageMetaDataRecord]:
    """Parse ImageMetaData CSV file."""
    records = []
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                normalized = _normalize_field_names(row, IMAGE_META_FIELD_MAP)
                try:
                    record = ImageMetaDataRecord(
                        exposure_number=_safe_int(normalized.get("exposure_number", 0)) or 0,
                        file_path=normalized.get("file_path"),
                        filter_name=normalized.get("filter_name", "Unknown"),
                        exposure_start=normalized.get("exposure_start", ""),
                        exposure_start_utc=normalized.get("exposure_start_utc", ""),
                        duration=_safe_float(normalized.get("duration")) or 0.0,
                        binning=normalized.get("binning"),
                        camera_temp=_safe_float(normalized.get("camera_temp")),
                        camera_target_temp=_safe_float(normalized.get("camera_target_temp")),
                        gain=_safe_int(normalized.get("gain")),
                        offset=_safe_int(normalized.get("offset")),
                        adu_mean=_safe_float(normalized.get("adu_mean")),
                        adu_median=_safe_float(normalized.get("adu_median")),
                        adu_stdev=_safe_float(normalized.get("adu_stdev")),
                        adu_min=_safe_int(normalized.get("adu_min")),
                        adu_max=_safe_int(normalized.get("adu_max")),
                        hfr=_safe_float(normalized.get("hfr")),
                        hfr_stdev=_safe_float(normalized.get("hfr_stdev")),
                        detected_stars=_safe_int(normalized.get("detected_stars")),
                        fwhm=_safe_float(normalized.get("fwhm")),
                        eccentricity=_safe_float(normalized.get("eccentricity")),
                        guiding_rms=_safe_float(normalized.get("guiding_rms")),
                        guiding_rms_arcsec=_safe_float(normalized.get("guiding_rms_arcsec")),
                        guiding_rms_ra=_safe_float(normalized.get("guiding_rms_ra")),
                        guiding_rms_ra_arcsec=_safe_float(normalized.get("guiding_rms_ra_arcsec")),
                        guiding_rms_dec=_safe_float(normalized.get("guiding_rms_dec")),
                        guiding_rms_dec_arcsec=_safe_float(normalized.get("guiding_rms_dec_arcsec")),
                        focuser_position=_safe_int(normalized.get("focuser_position")),
                        focuser_temp=_safe_float(normalized.get("focuser_temp")),
                        rotator_position=_safe_float(normalized.get("rotator_position")),
                        pier_side=normalized.get("pier_side"),
                        airmass=_safe_float(normalized.get("airmass")),
                        mount_ra=_safe_float(normalized.get("mount_ra")),
                        mount_dec=_safe_float(normalized.get("mount_dec")),
                        image_type=normalized.get("image_type"),
                    )
                    records.append(record)
                except Exception as e:
                    logger.warning(f"Error parsing ImageMetaData CSV row: {e}")
                    continue

    except Exception as e:
        logger.error(f"Error parsing ImageMetaData CSV: {e}")

    return records


def parse_weather_data_json(file_path: str) -> List[WeatherDataRecord]:
    """Parse WeatherData JSON file."""
    records = []
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        if not isinstance(data, list):
            data = [data]

        for item in data:
            normalized = _normalize_field_names(item, WEATHER_FIELD_MAP)
            try:
                record = WeatherDataRecord(
                    exposure_number=_safe_int(normalized.get("exposure_number", 0)) or 0,
                    exposure_start=normalized.get("exposure_start", ""),
                    exposure_start_utc=normalized.get("exposure_start_utc", ""),
                    temperature=_safe_float(normalized.get("temperature")),
                    dew_point=_safe_float(normalized.get("dew_point")),
                    humidity=_safe_float(normalized.get("humidity")),
                    pressure=_safe_float(normalized.get("pressure")),
                    wind_speed=_safe_float(normalized.get("wind_speed")),
                    wind_direction=_safe_float(normalized.get("wind_direction")),
                    wind_gust=_safe_float(normalized.get("wind_gust")),
                    cloud_cover=_safe_float(normalized.get("cloud_cover")),
                    sky_temperature=_safe_float(normalized.get("sky_temperature")),
                    sky_brightness=_safe_float(normalized.get("sky_brightness")),
                    sky_quality=_safe_float(normalized.get("sky_quality")),
                )
                records.append(record)
            except Exception as e:
                logger.warning(f"Error parsing WeatherData record: {e}")
                continue

    except Exception as e:
        logger.error(f"Error parsing WeatherData JSON: {e}")

    return records


def parse_weather_data_csv(file_path: str) -> List[WeatherDataRecord]:
    """Parse WeatherData CSV file."""
    records = []
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                normalized = _normalize_field_names(row, WEATHER_FIELD_MAP)
                try:
                    record = WeatherDataRecord(
                        exposure_number=_safe_int(normalized.get("exposure_number", 0)) or 0,
                        exposure_start=normalized.get("exposure_start", ""),
                        exposure_start_utc=normalized.get("exposure_start_utc", ""),
                        temperature=_safe_float(normalized.get("temperature")),
                        dew_point=_safe_float(normalized.get("dew_point")),
                        humidity=_safe_float(normalized.get("humidity")),
                        pressure=_safe_float(normalized.get("pressure")),
                        wind_speed=_safe_float(normalized.get("wind_speed")),
                        wind_direction=_safe_float(normalized.get("wind_direction")),
                        wind_gust=_safe_float(normalized.get("wind_gust")),
                        cloud_cover=_safe_float(normalized.get("cloud_cover")),
                        sky_temperature=_safe_float(normalized.get("sky_temperature")),
                        sky_brightness=_safe_float(normalized.get("sky_brightness")),
                        sky_quality=_safe_float(normalized.get("sky_quality")),
                    )
                    records.append(record)
                except Exception as e:
                    logger.warning(f"Error parsing WeatherData CSV row: {e}")
                    continue

    except Exception as e:
        logger.error(f"Error parsing WeatherData CSV: {e}")

    return records


def parse_session_metadata_directory(directory: str) -> SessionMetadataResponse:
    """
    Parse all Session Metadata Plugin files in a directory.

    Looks for:
    - AcquisitionDetails.json or AcquisitionDetails.csv
    - ImageMetaData.json or ImageMetaData.csv
    - WeatherData.json or WeatherData.csv
    """
    dir_path = Path(directory)
    if not dir_path.exists():
        logger.error(f"Directory not found: {directory}")
        return SessionMetadataResponse()

    acquisition_details = None
    image_metadata: List[ImageMetaDataRecord] = []
    weather_data: List[WeatherDataRecord] = []
    file_count = 0

    # Look for AcquisitionDetails
    for ext in [".json", ".csv"]:
        acq_file = dir_path / f"AcquisitionDetails{ext}"
        if acq_file.exists():
            if ext == ".json":
                acquisition_details = parse_acquisition_details_json(str(acq_file))
            else:
                acquisition_details = parse_acquisition_details_csv(str(acq_file))
            if acquisition_details:
                file_count += 1
            break

    # Look for ImageMetaData
    for ext in [".json", ".csv"]:
        img_file = dir_path / f"ImageMetaData{ext}"
        if img_file.exists():
            if ext == ".json":
                image_metadata = parse_image_metadata_json(str(img_file))
            else:
                image_metadata = parse_image_metadata_csv(str(img_file))
            if image_metadata:
                file_count += 1
            break

    # Look for WeatherData
    for ext in [".json", ".csv"]:
        weather_file = dir_path / f"WeatherData{ext}"
        if weather_file.exists():
            if ext == ".json":
                weather_data = parse_weather_data_json(str(weather_file))
            else:
                weather_data = parse_weather_data_csv(str(weather_file))
            if weather_data:
                file_count += 1
            break

    return SessionMetadataResponse(
        acquisition_details=acquisition_details,
        image_metadata=image_metadata,
        weather_data=weather_data,
        file_count=file_count,
    )


def parse_session_metadata_from_content(
    acquisition_details_content: Optional[Tuple[str, str]] = None,  # (content, format: 'json'|'csv')
    image_metadata_content: Optional[Tuple[str, str]] = None,
    weather_data_content: Optional[Tuple[str, str]] = None,
) -> SessionMetadataResponse:
    """
    Parse Session Metadata from file content strings (for upload handling).

    Each tuple is (content_string, format) where format is 'json' or 'csv'.
    """
    import io

    acquisition_details = None
    image_metadata: List[ImageMetaDataRecord] = []
    weather_data: List[WeatherDataRecord] = []
    file_count = 0

    # Parse AcquisitionDetails
    if acquisition_details_content:
        content, fmt = acquisition_details_content
        if fmt == "json":
            try:
                data = json.loads(content)
                normalized = _normalize_field_names(data, ACQUISITION_FIELD_MAP)
                acquisition_details = AcquisitionDetails(
                    target_name=normalized.get("target_name", "Unknown"),
                    ra_coordinates=normalized.get("ra_coordinates"),
                    dec_coordinates=normalized.get("dec_coordinates"),
                    telescope_name=normalized.get("telescope_name"),
                    focal_length=_safe_float(normalized.get("focal_length")),
                    focal_ratio=_safe_float(normalized.get("focal_ratio")),
                    camera_name=normalized.get("camera_name"),
                    pixel_size=_safe_float(normalized.get("pixel_size")),
                    bit_depth=_safe_int(normalized.get("bit_depth")),
                    observer_latitude=_safe_float(normalized.get("observer_latitude")),
                    observer_longitude=_safe_float(normalized.get("observer_longitude")),
                    observer_elevation=_safe_float(normalized.get("observer_elevation")),
                )
                file_count += 1
            except Exception as e:
                logger.error(f"Error parsing AcquisitionDetails JSON content: {e}")
        elif fmt == "csv":
            try:
                reader = csv.DictReader(io.StringIO(content))
                for row in reader:
                    normalized = _normalize_field_names(row, ACQUISITION_FIELD_MAP)
                    acquisition_details = AcquisitionDetails(
                        target_name=normalized.get("target_name", "Unknown"),
                        ra_coordinates=normalized.get("ra_coordinates"),
                        dec_coordinates=normalized.get("dec_coordinates"),
                        telescope_name=normalized.get("telescope_name"),
                        focal_length=_safe_float(normalized.get("focal_length")),
                        focal_ratio=_safe_float(normalized.get("focal_ratio")),
                        camera_name=normalized.get("camera_name"),
                        pixel_size=_safe_float(normalized.get("pixel_size")),
                        bit_depth=_safe_int(normalized.get("bit_depth")),
                        observer_latitude=_safe_float(normalized.get("observer_latitude")),
                        observer_longitude=_safe_float(normalized.get("observer_longitude")),
                        observer_elevation=_safe_float(normalized.get("observer_elevation")),
                    )
                    file_count += 1
                    break
            except Exception as e:
                logger.error(f"Error parsing AcquisitionDetails CSV content: {e}")

    # Parse ImageMetaData
    if image_metadata_content:
        content, fmt = image_metadata_content
        if fmt == "json":
            try:
                data = json.loads(content)
                if not isinstance(data, list):
                    data = [data]
                for item in data:
                    normalized = _normalize_field_names(item, IMAGE_META_FIELD_MAP)
                    record = ImageMetaDataRecord(
                        exposure_number=_safe_int(normalized.get("exposure_number", 0)) or 0,
                        file_path=normalized.get("file_path"),
                        filter_name=normalized.get("filter_name", "Unknown"),
                        exposure_start=normalized.get("exposure_start", ""),
                        exposure_start_utc=normalized.get("exposure_start_utc", ""),
                        duration=_safe_float(normalized.get("duration")) or 0.0,
                        binning=normalized.get("binning"),
                        camera_temp=_safe_float(normalized.get("camera_temp")),
                        camera_target_temp=_safe_float(normalized.get("camera_target_temp")),
                        gain=_safe_int(normalized.get("gain")),
                        offset=_safe_int(normalized.get("offset")),
                        adu_mean=_safe_float(normalized.get("adu_mean")),
                        adu_median=_safe_float(normalized.get("adu_median")),
                        adu_stdev=_safe_float(normalized.get("adu_stdev")),
                        adu_min=_safe_int(normalized.get("adu_min")),
                        adu_max=_safe_int(normalized.get("adu_max")),
                        hfr=_safe_float(normalized.get("hfr")),
                        hfr_stdev=_safe_float(normalized.get("hfr_stdev")),
                        detected_stars=_safe_int(normalized.get("detected_stars")),
                        fwhm=_safe_float(normalized.get("fwhm")),
                        eccentricity=_safe_float(normalized.get("eccentricity")),
                        guiding_rms=_safe_float(normalized.get("guiding_rms")),
                        guiding_rms_arcsec=_safe_float(normalized.get("guiding_rms_arcsec")),
                        guiding_rms_ra=_safe_float(normalized.get("guiding_rms_ra")),
                        guiding_rms_ra_arcsec=_safe_float(normalized.get("guiding_rms_ra_arcsec")),
                        guiding_rms_dec=_safe_float(normalized.get("guiding_rms_dec")),
                        guiding_rms_dec_arcsec=_safe_float(normalized.get("guiding_rms_dec_arcsec")),
                        focuser_position=_safe_int(normalized.get("focuser_position")),
                        focuser_temp=_safe_float(normalized.get("focuser_temp")),
                        rotator_position=_safe_float(normalized.get("rotator_position")),
                        pier_side=normalized.get("pier_side"),
                        airmass=_safe_float(normalized.get("airmass")),
                        mount_ra=_safe_float(normalized.get("mount_ra")),
                        mount_dec=_safe_float(normalized.get("mount_dec")),
                        image_type=normalized.get("image_type"),
                    )
                    image_metadata.append(record)
                if image_metadata:
                    file_count += 1
            except Exception as e:
                logger.error(f"Error parsing ImageMetaData JSON content: {e}")
        elif fmt == "csv":
            try:
                reader = csv.DictReader(io.StringIO(content))
                for row in reader:
                    normalized = _normalize_field_names(row, IMAGE_META_FIELD_MAP)
                    record = ImageMetaDataRecord(
                        exposure_number=_safe_int(normalized.get("exposure_number", 0)) or 0,
                        file_path=normalized.get("file_path"),
                        filter_name=normalized.get("filter_name", "Unknown"),
                        exposure_start=normalized.get("exposure_start", ""),
                        exposure_start_utc=normalized.get("exposure_start_utc", ""),
                        duration=_safe_float(normalized.get("duration")) or 0.0,
                        binning=normalized.get("binning"),
                        camera_temp=_safe_float(normalized.get("camera_temp")),
                        camera_target_temp=_safe_float(normalized.get("camera_target_temp")),
                        gain=_safe_int(normalized.get("gain")),
                        offset=_safe_int(normalized.get("offset")),
                        adu_mean=_safe_float(normalized.get("adu_mean")),
                        adu_median=_safe_float(normalized.get("adu_median")),
                        adu_stdev=_safe_float(normalized.get("adu_stdev")),
                        adu_min=_safe_int(normalized.get("adu_min")),
                        adu_max=_safe_int(normalized.get("adu_max")),
                        hfr=_safe_float(normalized.get("hfr")),
                        hfr_stdev=_safe_float(normalized.get("hfr_stdev")),
                        detected_stars=_safe_int(normalized.get("detected_stars")),
                        fwhm=_safe_float(normalized.get("fwhm")),
                        eccentricity=_safe_float(normalized.get("eccentricity")),
                        guiding_rms=_safe_float(normalized.get("guiding_rms")),
                        guiding_rms_arcsec=_safe_float(normalized.get("guiding_rms_arcsec")),
                        guiding_rms_ra=_safe_float(normalized.get("guiding_rms_ra")),
                        guiding_rms_ra_arcsec=_safe_float(normalized.get("guiding_rms_ra_arcsec")),
                        guiding_rms_dec=_safe_float(normalized.get("guiding_rms_dec")),
                        guiding_rms_dec_arcsec=_safe_float(normalized.get("guiding_rms_dec_arcsec")),
                        focuser_position=_safe_int(normalized.get("focuser_position")),
                        focuser_temp=_safe_float(normalized.get("focuser_temp")),
                        rotator_position=_safe_float(normalized.get("rotator_position")),
                        pier_side=normalized.get("pier_side"),
                        airmass=_safe_float(normalized.get("airmass")),
                        mount_ra=_safe_float(normalized.get("mount_ra")),
                        mount_dec=_safe_float(normalized.get("mount_dec")),
                        image_type=normalized.get("image_type"),
                    )
                    image_metadata.append(record)
                if image_metadata:
                    file_count += 1
            except Exception as e:
                logger.error(f"Error parsing ImageMetaData CSV content: {e}")

    # Parse WeatherData
    if weather_data_content:
        content, fmt = weather_data_content
        if fmt == "json":
            try:
                data = json.loads(content)
                if not isinstance(data, list):
                    data = [data]
                for item in data:
                    normalized = _normalize_field_names(item, WEATHER_FIELD_MAP)
                    record = WeatherDataRecord(
                        exposure_number=_safe_int(normalized.get("exposure_number", 0)) or 0,
                        exposure_start=normalized.get("exposure_start", ""),
                        exposure_start_utc=normalized.get("exposure_start_utc", ""),
                        temperature=_safe_float(normalized.get("temperature")),
                        dew_point=_safe_float(normalized.get("dew_point")),
                        humidity=_safe_float(normalized.get("humidity")),
                        pressure=_safe_float(normalized.get("pressure")),
                        wind_speed=_safe_float(normalized.get("wind_speed")),
                        wind_direction=_safe_float(normalized.get("wind_direction")),
                        wind_gust=_safe_float(normalized.get("wind_gust")),
                        cloud_cover=_safe_float(normalized.get("cloud_cover")),
                        sky_temperature=_safe_float(normalized.get("sky_temperature")),
                        sky_brightness=_safe_float(normalized.get("sky_brightness")),
                        sky_quality=_safe_float(normalized.get("sky_quality")),
                    )
                    weather_data.append(record)
                if weather_data:
                    file_count += 1
            except Exception as e:
                logger.error(f"Error parsing WeatherData JSON content: {e}")
        elif fmt == "csv":
            try:
                reader = csv.DictReader(io.StringIO(content))
                for row in reader:
                    normalized = _normalize_field_names(row, WEATHER_FIELD_MAP)
                    record = WeatherDataRecord(
                        exposure_number=_safe_int(normalized.get("exposure_number", 0)) or 0,
                        exposure_start=normalized.get("exposure_start", ""),
                        exposure_start_utc=normalized.get("exposure_start_utc", ""),
                        temperature=_safe_float(normalized.get("temperature")),
                        dew_point=_safe_float(normalized.get("dew_point")),
                        humidity=_safe_float(normalized.get("humidity")),
                        pressure=_safe_float(normalized.get("pressure")),
                        wind_speed=_safe_float(normalized.get("wind_speed")),
                        wind_direction=_safe_float(normalized.get("wind_direction")),
                        wind_gust=_safe_float(normalized.get("wind_gust")),
                        cloud_cover=_safe_float(normalized.get("cloud_cover")),
                        sky_temperature=_safe_float(normalized.get("sky_temperature")),
                        sky_brightness=_safe_float(normalized.get("sky_brightness")),
                        sky_quality=_safe_float(normalized.get("sky_quality")),
                    )
                    weather_data.append(record)
                if weather_data:
                    file_count += 1
            except Exception as e:
                logger.error(f"Error parsing WeatherData CSV content: {e}")

    return SessionMetadataResponse(
        acquisition_details=acquisition_details,
        image_metadata=image_metadata,
        weather_data=weather_data,
        file_count=file_count,
    )
